#!/bin/sh

# This is an interdiff(1) testcase.
# Test: Final hunk should retain 'earlier' context.
# https://fedorahosted.org/patchutils/ticket/32


. ${top_srcdir-.}/tests/common.sh

cat << EOF > patch1
--- file.orig
+++ file
@@ -1,7 +1,7 @@
 1
 2
 3
-3
+4
 5
 6
 7
EOF

cat <<EOF > patch2
--- file.orig
+++ file
@@ -1,8 +1,9 @@
 1
 2
 3
-3
+4
 5
 6
 7
 8
+9
EOF

${INTERDIFF} patch1 patch2 > patch1-2 2>errors || exit 1
[ -s errors ] && exit 1

cat << EOF | cmp - patch1-2 || exit 1
diff -u file file
--- file
+++ file
@@ -6,3 +6,4 @@
 6
 7
 8
+9
EOF
