#!/bin/sh

# This is a recountdiff(1) testcase.
# Test: Test that empty hunks work.


. ${top_srcdir-.}/tests/common.sh

cat << EOF > patch
--- file
+++ file
@@ -1 +1 @@
-1
@@ -10 +10 @@
-1
+1
--- otherfile
+++ otherfile
@@ -1 +1 @@
+2
@@ -10 +10 @@
-1
+1
EOF

${RECOUNTDIFF} patch > patch-recounted || exit 1
cat << EOF | cmp - patch-recounted || exit 1
--- file
+++ file
@@ -1 +0,0 @@
-1
@@ -10 +9 @@
-1
+1
--- otherfile
+++ otherfile
@@ -0,0 +1 @@
+2
@@ -10 +11 @@
-1
+1
EOF
