#!/bin/sh

# This is a flipdiff(1) testcase.


. ${top_srcdir-.}/tests/common.sh

cat << EOF > file.orig
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
EOF
cat << EOF > file
1
2
3
4
5
6
7
8
9
10
11
12 modify
13
14
15
16
17
18
19
EOF

${DIFF} -u file.orig file > patch1
mv -f file file.orig

cat << EOF > file
1
1 insert
2 insert
3 insert
4 insert
5 insert
6 insert
7 insert
8 insert
9 insert
10 insert
2
3
4
5
6
7
8
9
10
11
12 modify
13
14
15
16
16 insert
17
18
19
EOF

${DIFF} -u file.orig file > patch2

${FLIPDIFF} patch1 patch2 > patch-flipped || exit 1
sed -e "s/$(/bin/echo -ne '\t').*$//" patch-flipped > patch-cmp
cmp - patch-cmp << EOF || exit 1
--- file.orig
+++ file
@@ -1,4 +1,14 @@
 1
+1 insert
+2 insert
+3 insert
+4 insert
+5 insert
+6 insert
+7 insert
+8 insert
+9 insert
+10 insert
 2
 3
 4
@@ -14,6 +24,7 @@
 14
 15
 16
+16 insert
 17
 18
 19

=== 8< === cut here === 8< ===

--- file.orig
+++ file
@@ -19,7 +19,7 @@
 9
 10
 11
-12
+12 modify
 13
 14
 15
EOF
