#!/bin/sh

# This is an interdiff(1) testcase.
# Test: Fuzzy diffing test of the optional N argument to --fuzzy. Triggers
# rejects by setting the fuzz value to 1, when it could've been fuzzed with the
# default fuzz value of 2 in `patch`.


. ${top_srcdir-.}/tests/common.sh

cat << 'EOF' > patch1
--- file
+++ file
@@ -5,9 +5,6 @@
 line 5
 if
 1
-fi
-if
-2
 fi
 A
 B
EOF

cat << 'EOF' > patch2
--- file
+++ file
@@ -50,9 +50,6 @@
 line 6
 if
 1
-fi
-if
-2
 fi
 B
 C
EOF

cat << 'EOF' > expected
================================================================================
*    DELTA DIFFERENCES - code changes that differ between the patches          *
================================================================================

--- file
+++ file
@@ -7,4 +7,7 @@
 1
 fi
+if
+2
+fi
 A
 B

################################################################################
!    REJECTED PATCH2 HUNKS - could not be compared; manual review needed       !
################################################################################

--- file
+++ file
@@ -50,9 +50,6 @@
 line 6
 if
 1
-fi
-if
-2
 fi
 B
 C

================================================================================
*    CONTEXT DIFFERENCES - surrounding code differences between the patches    *
================================================================================

--- file
+++ file
@@ -7,3 +8,2 @@
 fi
-A
 B
EOF

${INTERDIFF} --fuzzy=1 patch1 patch2 2>errors >output
[ -s errors ] && exit 1

cmp output expected || exit 1
