#!/bin/sh

# This is a rediff(1) testcase.
# Test: Trim context from beginning and end of hunk.


. ${top_srcdir-.}/tests/common.sh

cat << EOF > original-patch
--- file.orig
+++ file
@@ -6,7 +6,7 @@
 trim me
 blah
 blah
-not
+important
 blah
 blah
 trim me
EOF

sed -e '/^ trim me$/d' original-patch > edited-patch

${REDIFF} original-patch edited-patch 2>errors >rediffed-patch || exit 1
[ -s errors ] && exit 1
cat << EOF | cmp - rediffed-patch || exit 1
--- file.orig
+++ file
@@ -7,5 +7,5 @@
 blah
 blah
-not
+important
 blah
 blah
EOF
