#!/bin/sh

# This is a recountdiff(1) testcase.
# Test: Fix bug with new files when git signature lines are present (issue #49).

. ${top_srcdir-.}/tests/common.sh

cat <<"EOF" > patch
diff --git a/test_file b/test_file
new file mode 100644
index 0000000..83db48f
--- /dev/null
+++ b/test_file
@@ -0,0 +1,3 @@
+line1
+line2
+line3
-- 
2.50.1

EOF

${RECOUNTDIFF} patch > patch-recounted || exit 1
cat <<"EOF" | cmp - patch-recounted || exit 1
diff --git a/test_file b/test_file
new file mode 100644
index 0000000..83db48f
--- /dev/null
+++ b/test_file
@@ -0,0 +1,3 @@
+line1
+line2
+line3
-- 
2.50.1

EOF
