#!/bin/sh

# This is a flipdiff(1) testcase.


. ${top_srcdir-.}/tests/common.sh

cat << EOF > patch1
--- file.orig
+++ file
@@ -5,7 +5,7 @@
 Changed this.
 
 Changed that.
-Borke it.
+Broke it.
 
 Fixed it again.
 Fixed it.
@@ -16,6 +16,7 @@
 Blah
 Blah
 Blah
+Foo
 Blah
 Blah
 Blah
EOF

cat << EOF > patch2
--- file.orig
+++ file
@@ -13,3 +13,3 @@
 Blah
-blah
+Blah
 Blah
EOF

${FLIPDIFF} patch1 patch2 > patch-flipped || exit 1
sed -e "s/$(/bin/echo -ne '\t').*$//" patch-flipped > patch-cmp
cmp - patch-flipped << EOF || exit 1
--- file.orig
+++ file
@@ -13,5 +13,5 @@
 Blah
-blah
+Blah
 Blah
 Blah
 Blah

=== 8< === cut here === 8< ===

--- file.orig
+++ file
@@ -5,7 +5,7 @@
 Changed this.
 
 Changed that.
-Borke it.
+Broke it.
 
 Fixed it again.
 Fixed it.
@@ -16,6 +16,7 @@
 Blah
 Blah
 Blah
+Foo
 Blah
 Blah
 Blah
EOF
