#!/bin/sh

# This is a patchview(1) testcase.


. ${top_srcdir-.}/tests/common.sh

cat << EOF > diff
--- file1
+++ file1
@@ -0,0 +1 @@
+a
--- orig/file2
+++ file2
@@ -0,0 +1 @@
+a
--- file3
+++ file3.orig
@@ -0,0 +1 @@
+a
EOF

${PATCHVIEW} diff 2>errors >index || exit 1
[ -s errors ] && exit 1

cat << EOF | cmp - index || exit 1
File #1  	file1
File #2  	file2
File #3  	file3
EOF
