#!/bin/sh

# This is a filterdiff(1) testcase.
# Test: Unified format, filename pattern and hunk selector


. ${top_srcdir-.}/tests/common.sh

cat << EOF > patch
--- a.orig
+++ a
@@ -1 +1 @@
-a
+b
--- b.orig
+++ b
@@ -2 +2,2 @@
-a
+b
+c
@@ -50 +51 @@
-a
+b
--- c.orig
+++ c
@@ -3 +3 @@
-a
+b
EOF

${FILTERDIFF} -i b --hunks=1 <patch >selected 2>errors || exit 1
[ -s errors ] && exit 1

cat << EOF | cmp - selected || exit 1
--- b.orig
+++ b
@@ -2 +2,2 @@
-a
+b
+c
EOF
