#!/bin/sh

# This is a recountdiff(1) testcase.
# Test: Avoid a bug in handling entirely-added files.


. ${top_srcdir-.}/tests/common.sh

cat <<"EOF" > patch
--- file
+++ file
@@ -389,5 +398,6 @@

	while (1)
 		;
+	# not needed
 	# at all
	# stop

EOF

${RECOUNTDIFF} patch > patch-recounted || exit 1
cat <<"EOF" | cmp - patch-recounted || exit 1
--- file
+++ file
@@ -389,6 +389,7 @@

	while (1)
 		;
+	# not needed
 	# at all
	# stop

EOF
