#!/bin/sh

# This is a filterdiff(1) testcase.
# Deal with git format-patch output more intelligently.

. ${top_srcdir-.}/tests/common.sh

cat <<"EOF" > git-output
diff --git a/ChangeLog b/ChangeLog
index aff7a94..304bef5 100644
--- a/ChangeLog
+++ b/ChangeLog
@@ -1 +1 @@
-Should hide diff and index lines
+when not selected
diff --git a/otherfile b/otherfile
index 5feceb9..dde7898 10644
--- a/otherfile
+++ b/otherfile
@@ -1 +1 @@
-This file will
+be selected
EOF

${LSDIFF} -n git-output 2>errors >index || exit 1
[ -s errors ] && exit 1
cat <<"EOF" | cmp - index || exit 1
1	a/ChangeLog
8	a/otherfile
EOF

${FILTERDIFF} -p1 -i otherfile git-output 2>errors >otherfile.patch || exit 1
[ -s errors ] && exit 1
cat <<"EOF" | cmp - otherfile.patch || exit 1
diff --git a/otherfile b/otherfile
index 5feceb9..dde7898 10644
--- a/otherfile
+++ b/otherfile
@@ -1 +1 @@
-This file will
+be selected
EOF
