#!/bin/sh

# This is an interdiff(1) testcase.
# Test: Fuzzy diffing with more than one rejected hunk per patched file. This
# also tests the hunk parser by inserting whitespace between the +++ line and
# the first hunk, which should be gracefully ignored.


. ${top_srcdir-.}/tests/common.sh

cat << 'EOF' > patch1
--- file
+++ file



@@ -5,9 +5,6 @@
 line 5
 if
 1
-fi
-if
-2
 fi
 A
 B
@@ -7,7 +7,7 @@
 C
 9
 8
-1
+7
 D
 E
 if
EOF

cat << 'EOF' > patch2
--- file
+++ file

@@ -50,9 +50,6 @@
 line 6
 if
 1
-fi
-if
-2
 fi
 B
 C
@@ -7,7 +7,7 @@
 D
 Z
 1
-1
+7
 F
 E
 if
EOF

cat << 'EOF' > expected
================================================================================
*    DELTA DIFFERENCES - code changes that differ between the patches          *
================================================================================

--- file
+++ file
@@ -6,8 +6,8 @@
 if
 1
 fi
+if
+2
+fi
 A
 B
-D
-E
-if

################################################################################
!    REJECTED PATCH2 HUNKS - could not be compared; manual review needed       !
################################################################################

--- file
+++ file
@@ -50,9 +50,6 @@
 line 6
 if
 1
-fi
-if
-2
 fi
 B
 C
@@ -7,7 +7,7 @@
 D
 Z
 1
-1
+7
 F
 E
 if

================================================================================
*    CONTEXT DIFFERENCES - surrounding code differences between the patches    *
================================================================================

--- file
+++ file
@@ -2 +2,0 @@
-line 5
@@ -8,3 +15,2 @@
 fi
-A
 B
EOF

${INTERDIFF} --fuzzy=1 patch1 patch2 2>errors >output
[ -s errors ] && exit 1

cmp output expected || exit 1
