#!/bin/sh

# This is a flipdiff(1) testcase.


. ${top_srcdir-.}/tests/common.sh

cat << EOF > file.orig
a
b
c
d
e
f
g
h
i
j
k
l
EOF

cat << EOF > file
a
b
apple
banana
cat
dog
d
e
f
g
h
i
j
k
l
EOF

${DIFF} -u file.orig file > patch1

mv -f file file.orig
cat << EOF > file
a
b
elephant
apple
banana
cat
dog
d
e
f
g
h
i
j
k
l
EOF

${DIFF} -u file.orig file > patch2

${FLIPDIFF} patch1 patch2 > patch-flipped || exit 1
sed -e "s/$(/bin/echo -ne '\t').*$//" patch-flipped > patch-cmp
cmp - patch-cmp << EOF || exit 1
--- file.orig
+++ file
@@ -1,5 +1,6 @@
 a
 b
+elephant
 c
 d
 e

=== 8< === cut here === 8< ===

--- file.orig
+++ file
@@ -1,7 +1,10 @@
 a
 b
 elephant
-c
+apple
+banana
+cat
+dog
 d
 e
 f
EOF
