#!/bin/sh
#
# This is an interdiff(1) test case.
# Test: -U3 works correctly.


. ${top_srcdir-.}/tests/common.sh

cat << EOF > file.orig
one
two
three
EOF
cat << EOF > file
one
two
three
add some stuff
to the file
which had 3 lines
EOF
${DIFF} -U0 file.orig file > patch
${INTERDIFF} -U3 /dev/null patch 2>errors > interdiffed || exit 1
[ -s errors ] && exit 1
# Should be four lines beginning '+' (one in the header)
count=$(grep '^+' interdiffed | wc -l)
[ "$count" -eq 4 ] || exit 1
grep -q '^ ' interdiffed && exit 1
exit 0
