#!/bin/sh

# This is a rediff(1) testcase.
# Test: Add a hunk.


. ${top_srcdir-.}/tests/common.sh

cat << EOF > original-patch
--- file.orig
+++ file
@@ -37,7 +37,7 @@
 blah
 blah
 blah
-not
+important
 blah
 blah
 blah
EOF

cat << EOF > edited-patch
--- file.orig
+++ file
@@ -6,1 +5,0 @@
-no blah
@@ -37,7 +37,7 @@
 blah
 blah
 blah
-not
+important
 blah
 blah
 blah
EOF

${REDIFF} original-patch edited-patch 2>errors >rediffed-patch || exit 1
[ -s errors ] && exit 1
cat << EOF | cmp - rediffed-patch || exit 1
--- file.orig
+++ file
@@ -6 +5,0 @@
-no blah
@@ -37,7 +36,7 @@
 blah
 blah
 blah
-not
+important
 blah
 blah
 blah
EOF
