#!/bin/sh

# This is a rediff(1) testcase.
# Test: Remove a hunk.


. ${top_srcdir-.}/tests/common.sh

cat << EOF > edited-patch
--- file.orig
+++ file
@@ -37,6 +38,7 @@
 blah
 blah
 blah
+blah
 blah
 blah
 blah
EOF

cat << EOF > original-patch
--- file.orig
+++ file
@@ -6,6 +6,7 @@
 blah
 blah
 blah
+important
 blah
 blah
 blah
@@ -37,6 +38,7 @@
 blah
 blah
 blah
+blah
 blah
 blah
 blah
EOF

${REDIFF} original-patch edited-patch 2>errors >rediffed-patch || exit 1
[ -s errors ] && exit 1
cat << EOF | cmp - rediffed-patch || exit 1
--- file.orig
+++ file
@@ -37,6 +37,7 @@
 blah
 blah
 blah
+blah
 blah
 blah
 blah
EOF
