#!/bin/sh

# This is a lsdiff(1) testcase.
# Test: -nv output format, context input


. ${top_srcdir-.}/tests/common.sh

cat << EOF > diff
Here are some non-diff lines.
They should not be displayed by lsdiff -v.
*** file1
--- file1
***************
*** 0 ****
--- 1 ----
+ a
*** 60 ****
! a
--- 60 ----
! b
*** orig/file2
--- file2
***************
*** 0 ****
--- 1 ----
+ a
*** file3
--- file3.orig
***************
*** 0 ****
--- 1 ----
+ a
EOF

${LSDIFF} -nv diff 2>errors >index || exit 1
[ -s errors ] && exit 1

cat << EOF | cmp - index || exit 1
3	file1
	6	Hunk #1
	9	Hunk #2
13	file2
	16	Hunk #1
19	file3
	22	Hunk #1
EOF
