#!/bin/sh

# This is a grepdiff(1) testcase.


. ${top_srcdir-.}/tests/common.sh

cat << EOF > diff
--- file1
+++ file1
@@ -0,0 +1 @@
++a
--- orig/file2
+++ file2
@@ -0,0 +1 @@
+a
--- file3
+++ file3.orig
@@ -0,0 +1 @@
+b
EOF

# Check if PCRE2 is being used by examining the help output
if ${GREPDIFF} --help 2>&1 | grep -q "PCRE regexes are used by default"; then
    # PCRE2 is enabled - need to escape the plus sign
    PATTERN='\+a'
else
    # Standard regex - plus sign doesn't need escaping
    PATTERN='+a'
fi

${GREPDIFF} "$PATTERN" diff 2>errors >index || exit 1
[ -s errors ] && exit 1

cat << EOF | cmp - index || exit 1
file1
EOF
