#!/bin/sh

. ${top_srcdir-.}/tests/common.sh

mkdir dir
cat << EOF > dir/file.orig
-- 
foo
bar
baz
bing
bong
bang
crash
wallop
EOF
cat << EOF > new1
-- 
foo
bar
baz
bing
bong
bang
crash
wallop
EOF
cat << EOF > new2
b
foo
bar
baz
bing
bong
bang
crash
wallop
thump
EOF

cp new1 dir/file
${DIFF} -u dir/file.orig dir/file > patch1
mkdir dir.modified
mv dir/file.orig dir/file
cp new2 dir.modified/file
${DIFF} -urN dir dir.modified > patch2
${INTERDIFF} patch1 patch2 2>errors > patch1-2 || exit 1
[ -s errors ] && exit 1
mkdir test
cp new1 test/file
cd test
${PATCH} < ../patch1-2 || exit 1
cd ..
cmp new2 test/file || exit 1
