#!/bin/sh

# This is a rediff(1) testcase.
# Test: --in-place option

. ${top_srcdir-.}/tests/common.sh

cat << "EOF" > patch.orig
--- file
+++ file
@@ -3,3 +3,4 @@
 1
 2
 3
+4.5
EOF

cat << "EOF" > patch.mod
--- file
+++ file
@@ -3,3 +3,4 @@
+4.5
EOF

# Test --in-place
${REDIFF} --in-place patch.orig patch.mod || exit 1

# Check that patch.mod was modified in place
cmp - patch.mod << "EOF" || exit 1
--- file
+++ file
@@ -6,0 +6 @@
+4.5
EOF
