#!/bin/sh

# This is a lsdiff(1) testcase.
# Test: --strip and --addprefix tests.


. ${top_srcdir-.}/tests/common.sh

mkdir dir dir.orig
echo a > dir.orig/a
echo A > dir/a
${DIFF} -uN dir.orig dir > diff
${LSDIFF} --addprefix=prefix/ --strip=1 diff 2>errors >index || exit 1
[ -s errors ] && exit 1

cat << EOF | cmp - index || exit 1
prefix/a
EOF

${FILTERDIFF} --addprefix=prefix/ --strip=1 diff 2>errors >filtered || exit 1
[ -z "${ERRPRS}" ] || exit 1

${LSDIFF} filtered 2>errors >filtered-index || exit 1
[ -z "${ERRPRS}" ] || exit 1

cat << EOF | cmp - filtered-index || exit 1
prefix/a
EOF
