#!/bin/sh

# This is an interdiff(1) testcase.
# Test: Fuzzy diffing with one rejected hunk per patched file.


. ${top_srcdir-.}/tests/common.sh

cat << 'EOF' > patch1
--- file
+++ file
@@ -1,4 +1,4 @@
-line 1
+LINE 1
 line 2
 line 3
 line 4
EOF

cat << 'EOF' > patch2
--- file
+++ file
@@ -5,9 +5,6 @@
 line 5
 if
 1
-fi
-if
-2
 fi
 A
 B
EOF

cat << 'EOF' > expected
================================================================================
*    DELTA DIFFERENCES - code changes that differ between the patches          *
================================================================================

--- file
+++ file
@@ -1,4 +1,4 @@
-LINE 1
+line 1
 line 2
 line 3
 line 4

################################################################################
!    REJECTED PATCH2 HUNKS - could not be compared; manual review needed       !
################################################################################

--- file
+++ file
@@ -5,9 +5,6 @@
 line 5
 if
 1
-fi
-if
-2
 fi
 A
 B

================================================================================
*    CONTEXT DIFFERENCES - surrounding code differences between the patches    *
================================================================================

--- file
+++ file
@@ -1,4 +1,9 @@
-line 1
-line 2
-line 3
-line 4
+line 5
+if
+1
+fi
+if
+2
+fi
+A
+B
EOF

${INTERDIFF} --fuzzy patch1 patch2 2>errors >output
[ -s errors ] && exit 1

cmp output expected || exit 1
