#!/bin/sh

# This is a flipdiff(1) testcase.


. ${top_srcdir-.}/tests/common.sh

cat << EOF > file.orig
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
EOF
cat << EOF > file
1
1 insert
2
3
4
5
6
7
8
9 modify
10
11
12
13
14
15
16
EOF

${DIFF} -u file.orig file > patch1
mv -f file file.orig

cat << EOF > file
1
1 insert
2
3
4
5
6 add some lines
7 add some lines
7 add some lines
8 add some lines
9 add some lines
10 add some lines
11 add some lines
12 add some lines
13 add some lines
14 add some lines
6
7
8
9 modify
10
11
12
13
14
15
16
EOF

${DIFF} -u file.orig file > patch2

${FLIPDIFF} patch1 patch2 > patch-flipped || exit 1
sed -e "s/$(/bin/echo -ne '\t').*$//" patch-flipped > patch-cmp
cmp - patch-cmp << EOF || exit 1
--- file.orig
+++ file
@@ -3,6 +3,16 @@
 3
 4
 5
+6 add some lines
+7 add some lines
+7 add some lines
+8 add some lines
+9 add some lines
+10 add some lines
+11 add some lines
+12 add some lines
+13 add some lines
+14 add some lines
 6
 7
 8

=== 8< === cut here === 8< ===

--- file.orig
+++ file
@@ -1,4 +1,5 @@
 1
+1 insert
 2
 3
 4
@@ -16,7 +17,7 @@
 6
 7
 8
-9
+9 modify
 10
 11
 12
EOF
