#!/bin/sh

# This is a recountdiff(1) testcase.
# Test: Test that it works.


. ${top_srcdir-.}/tests/common.sh

cat << EOF > patch
--- file
--- file -- fooled you!
+++ file
@@ -1 +1 @@
-1
+2
+3
@@ -10 +10 @@
-1
+1
--- otherfile
+++ otherfile
@@ -1 +1,2 @@
 1
-1
+2
EOF

${RECOUNTDIFF} patch > patch-recounted || exit 1
cat << EOF | cmp - patch-recounted || exit 1
--- file
--- file -- fooled you!
+++ file
@@ -1 +1,2 @@
-1
+2
+3
@@ -10 +11 @@
-1
+1
--- otherfile
+++ otherfile
@@ -1,2 +1,2 @@
 1
-1
+2
EOF
