#!/bin/sh

# This is a filterdiff(1) testcase.
# Test: Context format, filename pattern but no selector


. ${top_srcdir-.}/tests/common.sh

cat << EOF > patch
*** a.orig
--- a
***************
*** 1 ****
! a
--- 1 ----
! b
*** b.orig
--- b
***************
*** 1 ****
! a
--- 1 ----
! b
*** c.orig
--- c
***************
*** 1 ****
! a
--- 1 ----
! b
EOF

${FILTERDIFF} -i b <patch >selected 2>errors || exit 1
[ -s errors ] && exit 1

cat << EOF | cmp - selected || exit 1
*** b.orig
--- b
***************
*** 1 ****
! a
--- 1 ----
! b
EOF
