#!/bin/sh

# This is a filterdiff(1) testcase.
# Test: Unified format, --hunks but no -i or -x.


. ${top_srcdir-.}/tests/common.sh

cat << EOF > patch
--- a.orig
+++ a
@@ -1 +1 @@
-a
+b
--- b.orig
+++ b
@@ -2 +2,2 @@
-a
+b
+c
@@ -50 +51 @@
-a
+b
--- c.orig
+++ c
@@ -3 +3 @@
-a
+b
EOF

${FILTERDIFF} --hunks=2 <patch >selected 2>errors || exit 2
[ -s errors ] && exit 1

cat << EOF | cmp - selected || exit 1
--- b.orig
+++ b
@@ -50 +50 @@
-a
+b
EOF
