#!/bin/sh

# This is a lsdiff(1) testcase.
# Test: -Es output format, context input


. ${top_srcdir-.}/tests/common.sh

cat << EOF > diff
*** file1
--- file1
***************
*** 0 ****
--- 1 ----
+ a
*** 60 ****
! a
--- 60 ----
! b
*** orig/file2
--- file2
***************
*** 0 ****
--- 1 ----
+ a
*** file3
--- file3.orig
***************
*** 1 ****
- a
--- 0 ----
EOF

${LSDIFF} -Es diff 2>errors >index || exit 1
[ -s errors ] && exit 1

cat << EOF | cmp - index || exit 1
! file1
+ file2
- file3
EOF
