#!/bin/sh

# This is a rediff(1) testcase.
# Test: Add a hunk, filling in missing offsets and counts.


. ${top_srcdir-.}/tests/common.sh

cat << EOF > original-patch
--- file.orig
+++ file
@@ -6,7 +6,7 @@
 blah
 blah
 blah
-not
+important
 blah
 blah
 blah
EOF

cat original-patch - << EOF > edited-patch
@@ -37
 blah
 blah
 blah
+blah
 blah
 blah
 blah
EOF

${REDIFF} original-patch edited-patch 2>errors >rediffed-patch || exit 1
[ -s errors ] && exit 1
cat << EOF | cmp - rediffed-patch || exit 1
--- file.orig
+++ file
@@ -6,7 +6,7 @@
 blah
 blah
 blah
-not
+important
 blah
 blah
 blah
@@ -37,6 +37,7 @@
 blah
 blah
 blah
+blah
 blah
 blah
 blah
EOF
