#!/bin/sh

# This is a filterdiff(1) testcase.
# Test: Unified format, --as-numbered-lines=after


. ${top_srcdir-.}/tests/common.sh

cat << EOF > patch
--- a.orig
+++ a
@@ -1 +1 @@
-a
+b
--- b.orig
+++ b
@@ -2 +2,2 @@
-a
+b
+c
@@ -50 +51 @@
-a
+b
--- c.orig
+++ c
@@ -3 +3 @@
-a
+b
EOF

${FILTERDIFF} --as-numbered-lines=after -i b -#1 <patch >selected 2>errors || exit 1
[ -s errors ] && exit 1

cat << EOF | cmp - selected || exit 1
+++ b
2	:b
3	:c
EOF
