#!/bin/sh

# This is a flipdiff(1) testcase.


. ${top_srcdir-.}/tests/common.sh

cat << EOF > file.orig
a
b
c
EOF

cat << EOF > file
a
d
c
EOF

${DIFF} -u file.orig file > patch1

mv -f file file.orig
cat << EOF > file
a
c
d
EOF

${DIFF} -u file.orig file > patch2

${FLIPDIFF} patch1 patch2 > patch-flipped || exit 1
sed -e "s/$(/bin/echo -ne '\t').*$//" patch-flipped > patch-cmp
cmp - patch-cmp << EOF || exit 1
--- file.orig
+++ file
@@ -2,2 +2,2 @@
-b
 c
+d

=== 8< === cut here === 8< ===

EOF
